[build]
  # Static site deployment - no build process needed
  command = ""
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# Main headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Arabic language support
    Content-Language = "ar"
    
    # Content Security Policy for CDN libraries
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
        https://cdn.tailwindcss.com 
        https://cdn.jsdelivr.net
        https://cdnjs.cloudflare.com;
      style-src 'self' 'unsafe-inline' 
        https://cdn.tailwindcss.com 
        https://cdn.jsdelivr.net 
        https://fonts.googleapis.com
        https://cdnjs.cloudflare.com;
      font-src 'self' 
        https://fonts.gstatic.com 
        https://cdn.jsdelivr.net
        https://cdnjs.cloudflare.com;
      img-src 'self' data: https:;
      connect-src 'self' https:;
      media-src 'self';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """

# HTML files - no cache for dynamic content
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Vary = "Accept-Encoding"

# CSS and JS files - long cache
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Font files
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.woff"
  [headers.values]
    Content-Type = "font/woff"
    Cache-Control = "public, max-age=31536000, immutable"

# Image optimization
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Root redirect to main app
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Pretty URLs for main application files
[[redirects]]
  from = "/app"
  to = "/app-complete.html"
  status = 200
  
[[redirects]]
  from = "/family"
  to = "/family.html"
  status = 200

# Performance settings
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Form handling for future features
[forms]
  settings = { 
    error_page = "/404.html", 
    success_page = "/index.html" 
  }

# Edge functions placeholder for future enhancements
# [functions]
#   directory = "netlify/functions"