name = "saedan-family-tree"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

# Static site configuration for Cloudflare Pages
# The app uses a single index.html with all functionality
# No additional Workers or API endpoints needed

# Environment variables (optional)
# [env.production.vars]
# APP_VERSION = "2.0.0"
# DEBUG = "false"

# Build configuration
# Since this is a static HTML app, no complex build process needed
# Just copy index.html and assets to dist directory