# Cloudflare Pages Configuration
name = "saedan-family-tree"
compatibility_date = "2024-09-01"

# Static site configuration
[env.production]
compatibility_date = "2024-09-01"

[build]
# No build command needed for static HTML
command = ""
# The files to upload are in the root directory
publish = "./"

# Route configuration
[[env.production.routes]]
pattern = "*"
custom_domain = "saedan-familyapp.com"

# Environment variables (if needed)
[env.production.vars]
ENVIRONMENT = "production"